logger:
  image: alpine
  command: nc -lk -p 515
  ports:
    - "515:515"
tests:
  build: .
  command: pytest
  volumes:
    - ./:/usr/app
  links:
    - logger
  environment:
    - SYSLOG_HOST=logger
    - SYSLOG_PORT=515
