version: 2
jobs:
  build:
    working_directory: ~/winkapp/py-logger
    machine:
      enabled: true
    steps:
      - restore_cache:
          keys:
            - v1-git-{{ .Branch }}-{{ .Revision }}
            - v1-git-{{ .Branch }}-
      - checkout
      - save_cache:
          key: v1-git-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      # - run:
      #     name: Build Main Docker Image
      #     command: |
      #       docker build \
      #           --rm=false \
      #           -t quay.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 \
      #           -t quay.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH \
      #           .
      - run: docker-compose run tests
